### ISSUE TITLE
Error when trying to connect to Exchange Online

### ISSUE THREAD

**Issue by Gtrikoilis** [jborean93/pypsrp#73] opened 2020-05-17 23:52 UTC
I used to be able to connect using the below just fine
    
    from pypsrp.powershell import PowerShell, RunspacePool
    from pypsrp.wsman import WSMan
    import logging
    
    
    wsman = WSMan(
                "outlook.office365.com",
                port=443,
                path="powershell-liveid/",
                auth="basic",
                username="user@somewhere",
                password="password",
                cert_validation=False
            )
    with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
        ps = PowerShell(pool)
        ps.add_cmdlet("Get-Mailbox")
        output = ps.invoke()
but now i keep getting the below error

    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\wsman.py", line 756, in _send_request
        response.raise_for_status()
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 500 Server Error: Request Failed for url: https://outlook.office365.com:443/powershell-liveid/
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\wsman.py", line 378, in invoke
        response = self.transport.send(xml)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\wsman.py", line 735, in send
        return self._send_request(prep_request, hostname)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\wsman.py", line 765, in _send_request
        raise WinRMTransportError('http', code, response_text)
    pypsrp.exceptions.WinRMTransportError: Bad HTTP response returned from the server. Code: 500, Content: '<s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" xmlns:n="http://schemas.xmlsoap.org/ws/2004/09/enumeration" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.dmtf.org/wbem/wsman/1/wsman/fault</a:Action><a:MessageID>uuid:C1485CA1-4CAD-49E3-B3C8-30D03B5FEA7D</a:MessageID><p:ActivityId>3126A8C0-A23E-002A-562E-69B4F328D601</p:ActivityId><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:2F29F18E-1A3E-4BA3-AB50-3C7F9C1C03A5</a:RelatesTo></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value>w:InvalidSelectors</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">The WS-Management service cannot process the request because the request contained invalid selectors for the resource. </s:Text></s:Reason><s:Detail><w:FaultDetail>http://schemas.dmtf.org/wbem/wsman/1/wsman/faultDetail/UnexpectedSelectors</w:FaultDetail><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858843" Machine="outlook.office365.com"><f:Message>The request for the Windows Remote Shell with ShellId 4010B80A-D102-4022-B22B-E8591C0EC425 failed because the shell was not found on the server. Possible causes are: the specified ShellId is incorrect or the shell no longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation. </f:Message></f:WSManFault></s:Detail></s:Fault></s:Body></s:Envelope>'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "test.py", line 15, in <module>
        with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\powershell.py", line 200, in __enter__
        self.open()
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\powershell.py", line 513, in open
        responses.extend(self._receive())
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\powershell.py", line 636, in _receive
        timeout=timeout)[2]['stdout']
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\shell.py", line 241, in receive
        timeout=timeout)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\wsman.py", line 301, in receive
        option_set, selector_set, timeout)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\wsman.py", line 382, in invoke
        raise self._parse_wsman_fault(err.response_text)
    pypsrp.exceptions.WSManFaultError: Received a WSManFault message. (Code: 2150858843, Machine: outlook.office365.com, Reason: The request for the Windows Remote Shell with ShellId 4010B80A-D102-4022-B22B-E8591C0EC425 failed because the shell was not found on the server. Possible causes are: the specified ShellId is incorrect or the shell no longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation.)
    
    C:\Users\user\Desktop>python test.py
    Traceback (most recent call last):
      File "test.py", line 15, in <module>
        with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\powershell.py", line 200, in __enter__
        self.open()
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\powershell.py", line 513, in open
        responses.extend(self._receive())
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\powershell.py", line 637, in _receive
        return self._parse_responses(response, pipeline)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\powershell.py", line 681, in _parse_responses
        response_function = response_functions[message.message_type]
    KeyError: 266249
    
Any ideas please?

**Comment by jborean93** [comment] 2020-05-22 09:40
This is a duplicate of https://github.com/jborean93/pypsrp/issues/70. I am planning on getting to 70 at some point but right now there's not much you can do to fix this problem.

**Closed by jborean93** 2020-05-22 09:40 UTC
