### ISSUE TITLE
Got many urllib3 warnings.

### ISSUE THREAD

**Issue by AndrewTsao** [jborean93/pypsrp#55] opened 2019-09-20 10:54 UTC
After I call `logging.info` to output log, pypsrp work ok but output many urllib3 warnings. A simple case as follow.

```python
import logging as log
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

def test_psrp():
    log.info('hello')
    # creates a https connection with explicit kerberos auth and implicit credentials
    wsman = WSMan("192.168.5.43",
                  port=5985,
                  auth="credssp",
                  username="xxxx",
                  password="xxxx",
                  ssl=False)

    with RunspacePool(wsman) as pool:
        # execute 'Get-Process | Select-Object Name'
        ps = PowerShell(pool)
        ps.add_script(r'Start-Job -ScriptBlock { Python.exe  }')
        #ps.add_cmdlet("Get-Process")
        ps.add_cmdlet("Out-String").add_parameter("Stream")
        output = ps.invoke()
        if ps.had_errors:
            log.error(str(ps.streams.error[0]))
        print('\n'.join(output))

if __name__ == "__main__":
    test_psrp()

```

```
WARNING:urllib3.connectionpool:Failed to parse headers (url=http://192.168.5.43:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "e:\Projects\.venv\lib\site-packages\urllib3\connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "e:\Projects\.venv\lib\site-packages\urllib3\util\response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
```
My local encoding is GBK. Client Win7, Server is Windows 2012 R2。Python 3.6.4. urllib3 version is 1.25.3

Any suggests for this? Thank you.

**Comment by jborean93** [comment] 2019-09-24 14:38
This is a duplicate off https://github.com/jborean93/pypsrp/issues/39 and seems to be an underlying problem in urllib3, you can find out more info about this at https://github.com/diyan/pywinrm/issues/269. You should be able to suppress these warnings as they aren't an actual error by adding the following to your script for now (credit to https://github.com/diyan/pywinrm/issues/269#issuecomment-518523909).

```
class SuppressFilter(logging.Filter):
    def filter(self, record):
        return 'wsman' not in record.getMessage()
... ...
try:
    from urllib3.connectionpool import log
    log.addFilter(SuppressFilter())
except:
    pass
```

**Closed by jborean93** 2019-09-24 14:38 UTC
