### ISSUE TITLE
KeyError in serializer.py

### ISSUE THREAD

**Issue by gordonj7** [jborean93/pypsrp#3] opened 2018-08-07 22:41 UTC
I'm trying to access the `Get-MailboxStatistics` cmdlet with this code:

```
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

wsman = WSMan(server="outlook.office365.com", port=443,
    path="/powershell-liveid/", ssl="true", auth="basic",
    username="helpdesk_user@company.onmicrosoft.com",
    password="password")

with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
    ps = PowerShell(pool)
    ps.add_cmdlet("Get-MailboxStatistics").add_parameter("Identity", "gordonj")
    output = ps.invoke()
```

And I'm getting a `KeyError` way down deep in the module:

```
Traceback (most recent call last):
  File "sample.py", line 12, in <module>
    output = ps.invoke()
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/powershell.py", line 1072, in invoke
    return self.end_invoke()
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/powershell.py", line 1048, in end_invoke
    self.poll_invoke()
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/powershell.py", line 1223, in poll_invoke
    timeout=timeout)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/powershell.py", line 635, in _receive
    return self._parse_responses(response, pipeline)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/powershell.py", line 638, in _parse_responses
    messages = self._fragmenter.defragment(responses)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/powershell.py", line 1432, in defragment
    for fragment in fragments]
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/messages.py", line 186, in unpack
    message_data = serializer.deserialize(message_data)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 653, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 213, in deserialize
    return unpack_function(element)
  File "/home/gordonj/.local/lib/python2.7/site-packages/pypsrp/serializer.py", line 209, in <lambda>
    'Ref': lambda d: self.obj[d.attrib['RefId']],
KeyError: '44'
```

I am able to call other cmdlets such as `Get-Mailbox` and `Get-InboxRule` successfully.

Any ideas?

Thanks,

John Gordon
gordonj@illinois.edu

**Comment by jborean93** [comment] 2018-08-28 02:09
Sorry for not getting back to you sooner, would love to get a copy of the return objects to replicate this myself. Unfortunately I don't have an Office 365 subscription to test out the code. If you are ok with sharing the log output that would be great;

To enable logging, create a file called `log.json` with the following contents

```
{
    "version": 1,
    "disable_existing_loggers": false,
    "formatters": {
        "simple": {
            "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        }
    },

    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "level": "DEBUG",
            "formatter": "simple",
            "filename": "pypsrp.log",
            "mode": "w",
            "encoding": "utf-8"
        }
    },

    "loggers": {
        "pypsrp.messages": {
            "level": "DEBUG",
            "handlers": ["file"],
            "propagate": "no"
        }
    }
}
```

Run the Python script with the `PYPSRP_LOG_CFG=log.json` environment variable and a file called `pypsrp.log` will be created. Please make sure you are comfortable sharing the contents of the log online as this will contain all the PSRP messages sent to and from the client. If you aren't comfortable with this you can change/remove the values as I'm mostly interested in the structure/types and references in the message itself.

**Comment by gordonj7** [comment] 2018-08-28 22:51
I have some log output, and I'm looking it over to make sure it doesn't have anything sensitive.

**Comment by jborean93** [comment] 2018-08-28 23:02
The first few messages shouldn't be anything sensitive based on your example script, all the username/passwords are handled in a different section and shouldn't be in the output if you set `pypsrp.messages` in the loggers section. The last few messages may contain some sensitive information but it all depends on what `Get-MailboxStatistics` returns, I've never used that so can't really help you too much there.

**Comment by gordonj7** [comment] 2018-08-28 23:12
I'm working with the Windows admin here to make sure the log is safe.  I hope to post it in a day or two.

**Comment by jborean93** [comment] 2018-09-01 01:10
Ok, the issue is due to a circular dependency, the output you gave me has the following snippet

```
<Obj N="DomainId" RefId="44">
<TNRef RefId="6"/>
<ToString>com</ToString>
<Props>
    <Nil N="OrgHierarchyToIgnore"/>
    <B N="IsDeleted">false</B>
    <Obj N="Rdn" RefId="45">
        <TNRef RefId="7"/>
        <ToString>DC=com</ToString>
        <Props>
            <S N="Prefix">DC</S>
            <S N="EscapedName">com</S>
            <S N="UnescapedName">com</S>
        </Props>
    </Obj>
    <Nil N="Parent"/>
    <I32 N="Depth">0</I32>
    <S N="DistinguishedName">DC=com</S>
    <B N="IsRelativeDn">false</B>
    <Ref N="DomainId" RefId="44"/>
    <G N="PartitionGuid">00000000-0000-0000-0000-000000000000</G>
    <S N="PartitionFQDN">com</S>
    <G N="ObjectGuid">00000000-0000-0000-0000-000000000000</G>
    <S N="Name">com</S>
    <Nil N="SecurityIdentifierString"/>
</Props>
</Obj>
```

The `DomainId` property inside this object refers to itself and the current code hasn't finished creating the original object so there's no reference in the global reference table. I'll have a play around and see what I can come up with.

**Comment by jborean93** [comment] 2018-09-01 05:44
@gordonj7 I've opened a PR that should fix this https://github.com/jborean93/pypsrp/pull/5. If you have some time it would be great if you could test it out and let me know how you go.

**Comment by gordonj7** [comment] 2018-09-05 22:19
That fixed the error!  Thanks!

**Comment by jborean93** [comment] 2018-09-05 23:08
Thanks for the confirmation @gordonj7, I've merged the PR and will include a few other minor changes before I make a release. Thanks for your patience with this.

**Closed** 2018-09-05 23:07 UTC
